[package]
name = "walkfile"
version = "0.1.0"
edition = "2021"
description = "遍历指定目录下的所有文件夹，文件"
license = "MIT"
readme = "readme.md"
repository = "https://github.com/liuhuo23/app.git"

[dependencies]
anyhow = {workspace = true}